### ISSUE TITLE
Why we have property `_boundWheelEventListener` without defined type, or not defined with @property?

### ISSUE THREAD

**Issue by saas786** [conversionxl/aybolit#205]
Ref: https://github.com/conversionxl/aybolit/blob/eca5a549ba57820b08e1f880ee7c4d9c6169596f/packages/cxl-ui/src/components/cxl-app-layout.js#L61

It should have been:

```
  @property({ type: Function })
  _boundWheelEventListener;
```

instead of
```
  _boundWheelEventListener;
```

**Comment by lkraav** [comment]
This is @anoblet I believe.

**Comment by anoblet** [comment]
@saas786 `_boundWheelEventListener` stores a reference. It's there so that we can add/remove the listener depending on if either `wide` or `scroll` have changed (https://github.com/conversionxl/aybolit/blob/eca5a549ba57820b08e1f880ee7c4d9c6169596f/packages/cxl-ui/src/components/cxl-app-layout.js#L129).

Since we aren't setting it's state directly, but rather computing it's state from `wide` and `scroll`, there's no reason for the property to be "reactive".

The type parameter of the `property` decorator refers to the way `lit` reflects the property to an attribute. In this case, we are storing a reference to a listener. There's no need for the property to be reflected to an attribute.

https://lit.dev/docs/components/properties/

**Comment by saas786** [comment]
> [lit.dev/docs/components/properties](https://lit.dev/docs/components/properties/)

By default it doesn't reflect:
```
reflect

Whether property value is reflected back to the associated attribute. Default: false. For more information, see [Enabling attribute reflection](https://lit.dev/docs/components/properties/#reflected-attributes).
```

Every property have its purposes,  primarily to store the reference, data etc.
So this doesn't make it an exception.

Unless you find some performance, and code issues, I suggest we use `@property({ type: Function })`

**Comment by anoblet** [comment]
The property decorator's purpose is to create getters/setters and to call `requestUpdate`. `_boundEventListener` has no bearing on the UI and doesn't require this overhead.

**Comment by saas786** [comment]
> The property decorator's purpose is to create getters/setters and to call requestUpdate. _boundEventListener has no bearing on the UI and doesn't require this overhead.

Maybe you are correct, but in my opinion, decorator's are not limited to getters/setters usage. 
```
requestUpdate
```
Does this gets called when we set `@property({ type: Function })`? I don't think so, can test it out later.

**Comment by anoblet** [comment]
`@property` Registers the property with `lit` so that it is notified of changes and will call `requestUpdate` unless `hasChanged` has been overridden (https://lit.dev/docs/components/properties/#haschanged).
 
The type field is used for serialization/deserialization of the property to and from an attribute (https://lit.dev/docs/components/properties/#property-options). 

`function` is not supported out of the box as a default converter (https://lit.dev/docs/components/properties/#conversion-type).

**Comment by saas786** [comment]
I have tested

```
  // Event listener for the wheel event to allow scrolling from outside of the main pane.
  @property({ type: Function })
  _boundWheelEventListener;
```

Didn't found any trace of un-necessary
```
updated(changedProperties)
```

It was called only once when initiliazed.

While reviewing it, I noticed this var `_boundWheelEventListener` is un-necessary, so removed it altogeter.

See: https://github.com/conversionxl/aybolit/pull/207

@anoblet please test it out and let me know if it doesn't work as intended. Thanks.

**Comment by anoblet** [comment]
It works as intended because the event listener is registered with the component itself as opposed to the window.

https://lit.dev/docs/v1/components/events/#using-this-in-event-listeners
