### ISSUE TITLE
cxl-ui: can we support legacy browsers?

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#26]
See https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin

**Comment by saas786** [comment]
I had a look into "https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin" 
and it seemed fine, but its a dependency and I don't see any support behind the plugin either, also it can break our code etc.

Other option was we create two configs for **webpack** one for **legacy** and one for **modern** browsers and build two versions of JS. Which is quite useful.

But once I reviewed it, and tried to utilize it for **CXL-UI**, I realized we are using **Pika** instead of webpack for building packages.

So webpack was not helpful, specifically when we are using pika which behind the scenes uses RollUp.

And I had reviewed pika code if we can somehow pass some parameters to pika plugin to produce two separate files, but by default its not possible.

We have various plugins doing various things but plugin which is relevant to our need is

https://github.com/pikapkg/builders/tree/master/packages/plugin-bundle-web/

Creates a **ESM** build with all code (including dependencies) bundled. Useful for unpkg & serving code directly to browsers.


By default it produces code for modern browsers, though we can pass babel preset
ref: https://github.com/pikapkg/builders/blob/53aa9596c90484a18aa874382b9434e9807a40d8/packages/plugin-bundle-web/src/index.ts#L68

but there is no option to pass some config to it so it produces two files with different configs.

ref: https://github.com/pikapkg/builders/blob/53aa9596c90484a18aa874382b9434e9807a40d8/packages/plugin-bundle-web/src/index.ts#L78

I have reviewed existing plugins and this plugin comes close to what we need.

https://github.com/pikapkg/builders/tree/53aa9596c90484a18aa874382b9434e9807a40d8/packages/plugin-build-umd

It produces **"UMD"** files:

### Universal Module Definition, works as amd, cjs and iife all in one


I have found another plugin on npm registery:
https://www.npmjs.com/package/pika-plugin-legacy-browser

it produces "**iife**" output by default.

So either we use one of these two plugins or we build our own based on existing **@pika/plugin-bundle-web** and modify its output for legacy browsers.

Hopefully its useful.

**Comment by saas786** [comment]
I have managed to build **pika plugin** and used it in **cxl-ui** pipeline and it generates **es5** version of it.

I am still looking for a way to include polyfills dynamically / runtime while bundling the JS, but so far not sure. 

Maybe you can point out something in **RollUPJS** doing same.

Though I have manually added pollyfills and tested es5 code in chrome it seems to work, and in Edge works but have styling issues, in IE doesn't work, but doesn't throw any errors either.
tried any possible combination of custom elements polyfill I could find, but didn't render the layout like chrome.

https://medium.com/@xwatkins/making-vanilla-custom-elements-v1-work-in-ie11-64d3f09641b8

https://medium.com/@andrejsabrickis/make-polymer-2-0-web-components-work-on-ie11-and-edge-8d82eb1b9e5e

https://dev.to/bennypowers/lets-build-web-components-part-2-the-polyfills-dkh#supporting-ie11
use same polyfills as used here:

https://github.com/open-wc/open-wc/blob/2a7f869bd808a30be68ed1b0b6b59f305bd76536/packages/building-rollup/modern-and-legacy-config.js

tried
```
<script src="https://cdn.jsdelivr.net/npm/@webcomponents/custom-elements@1.3.1/custom-elements.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/@webcomponents/custom-elements@1.3.1/src/native-shim.js"></script>
```
or
`<script type="text/javascript" src="https://unpkg.com/@webcomponents/webcomponentsjs@2.4.0/webcomponents-bundle.js"></script>`

or (this make it work in chrome (proper), edge (styling issues), IE (doesn't throw any errors)

```
<script type="text/javascript" src="https://unpkg.com/@webcomponents/webcomponentsjs@2.4.0/custom-elements-es5-adapter.js"></script>

<script type="text/javascript" src="https://unpkg.com/polymer-build@2.1.1/lib/babel-helpers.min.js"></script>

<script type="text/javascript" src="https://unpkg.com/@webcomponents/webcomponentsjs@2.4.0/webcomponents-loader.js"></script>
```

Can the issue be with vaadin (not supporting IE11), or other components we are using for styling etc.
Also do you have any reference starter kit which works in IE11 (use custom elements, lit-html, vaadin etc)? So I can test code against it.

Let me know your thoughts.

**Comment by saas786** [comment]
es5 legacy code rendering with pollyfills

## IE View

![es5-legacy-code-ie-view](https://user-images.githubusercontent.com/1642796/69267459-ffcd7b80-0bee-11ea-9f36-48abcb1eae7c.jpg)

----------------------

## Chrome View

![es5-legacy-code-chrome-view](https://user-images.githubusercontent.com/1642796/69267460-00661200-0bef-11ea-97b7-b4838f2980b6.jpg)

----------------------

## Edge View

![es5-legacy-code-edge-view](https://user-images.githubusercontent.com/1642796/69267462-00fea880-0bef-11ea-9fae-64a520bcf721.jpg)

**Comment by lkraav** [comment]
Let's completely skip making things work for IE11.

But legacy Edge compatibility seems within reach. Find a consultant 
somewhere that can help figure out the details.

I will be at a conference for next 2 days, limited availability.

**Comment by saas786** [comment]
Here is my current analyses and research.

It seems like in Microsoft Edge, 

ShadyCSS is causing the issue I think.

It seems like webcomponents polyfill uses .style-scope classes to apply styles.

And in Edge it uses:

"html:not(.scope-style)"

Ref: https://github.com/webcomponents/shadycss/blob/60088439c734934e4fb1b6455abba1dde4fa8ef3/src/document-watcher.js#L91

this poly-fill forces it.

This explains the issue a bit more

https://github.com/vaadin/bookstore-starter-flow/issues/55#issuecomment-434347759

some extra info: 
https://github.com/vaadin/bookstore-starter-flow/issues/55#issuecomment-433879854

This article make few suggestions regarding how we should use styles:

https://www.codementor.io/bennyp/lets-build-web-components-part-2-the-polyfills-nzy0icg0c#dynamic-styles

https://www.codementor.io/bennyp/lets-build-web-components-part-2-the-polyfills-nzy0icg0c#shadycss-tldr

this explains if we write custom elements like this, then we can better utilize the pollyfills.

https://www.codementor.io/bennyp/lets-build-web-components-part-2-the-polyfills-nzy0icg0c#writing-custom-elements-that-work-with-the-polyfills

https://www.codementor.io/bennyp/lets-build-web-components-part-2-the-polyfills-nzy0icg0c#shadycss-rules

This issue my give you some more insights.
https://github.com/webcomponents/webcomponentsjs/issues/1009

This style is not being applied in Edge:

https://github.com/conversionxl/aybolit/blob/master/packages/cxl-lumo-styles/scss/color.scss#L8

From what I have explored today, somehow 

html, :host {}

doesn't work with shadycss pollyfill that with above info might give you idea of the issue.

Its not within the pollyfill domain that we just drop the polly fill and it should work.

Now it looks like we have to make them work with vaadin, lumo styles, custom elements & they way you are including css. All these factor into this.

Also I read somewhere that we should not have multiple ```<style>``` tags inside ```<template>``` or such and I saw multiple of them for like "lumo-default" or "lumo-styles" or something like that.

If you can create a minimal boilerplate or refer me similar boilerplate which uses tools you use and works in Edge, I can troubleshoot and find a balanced code which will work gracefully in browsers like Edge.

With current code I have to try too many changes and see if one might work. Which is not idea.

Let me know your thoughts.

**Comment by lkraav** [comment]
> With current code I have to try too many changes and see if one might work. Which is not idea.

We need pro consultation on this, instead of shooting in the dark.

I think pick another issue to target for time being.

**Comment by lkraav** [comment]
Talk about it at https://www.pika.dev/npm/@pika/web/discuss

**Comment by lkraav** [comment]
I think we're just going to skip working on this unless a solution organically appears on its own from somewhere.
